config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	resources :events do
		resources :schedules

	end

	resources :schedules do
		resources :days
	end

	# Route for File Downloads
	#get '/events/get/:id' => 'events#get'


	
	get '/home', to: 'page#home'
	get '/help', to: 'page#help'
	get '/about', to: 'page#about'

	authenticated :user do
		root 'events#index', as: "authenticated_root"
	end

	root "page#home"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
	belongs_to :event
	
	has_attached_file :uploaded_file, 
		:path => "assets/:id/:basename.:extension",
		:storage => :s3,
		:s3_credentials => "#{Rails.root}/config/amazon_s3.yml",
		:bucket => "eventdash",
		:url => ":s3_domain_url"
	do_not_validate_attachment_file_type :uploaded_file
	validates_attachment_size :uploaded_file, :less_than => 10.megabytes
	validates_attachment_presence :uploaded_file

	def file_name 
		uploaded_file_file_name 
	end
end

app/models/day.rb
class Day < ActiveRecord::Base
	belongs_to :schedule
	has_many :dayevents, dependent: :destroy

	accepts_nested_attributes_for :dayevents, allow_destroy: :true
end

app/models/dayevent.rb
class Dayevent < ActiveRecord::Base
  belongs_to :day
end

app/models/event.rb
class Event < ActiveRecord::Base
	before_save :sanitize_url
	belongs_to :user
	has_many :links, dependent: :destroy
	has_one :schedule, dependent: :destroy
	has_many :assets, dependent: :destroy
	has_many :days, through: :schedule

	accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :schedule, allow_destroy: true
	accepts_nested_attributes_for :assets, allow_destroy: true
	accepts_nested_attributes_for :days, allow_destroy: true

	validates :name, :description, presence: true

	private

	def sanitize_url
	   puts "Running Sanitize URL"
	   links.each do |lnk|
	   #	puts "Current Link URL : #{lnk.url}"
	   	lnk.url = "http://#{lnk.url}" unless lnk.url=~/^https?:\/\//
	   end
	    # url = "http://#{url}" unless url =~ /^https?:\/\//
	end 

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :event
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
	has_many :days, dependent: :destroy
	#attr_accessible :days_attributes

	accepts_nested_attributes_for :days, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :events
   has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

	def get
		asset = current_user.assets
	end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :show ]

  def index
    @events = current_user.events.all
  end

  def show
  end

  def new
    puts "runing new"
    @event = current_user.events.build
    @schedule = @event.build_schedule(event_id: @event.id, user_id: current_user.id)

  end

  def edit
    if @event.user_id != current_user.id
      flash[:error] = "Not allowed"
      redirect_to root_path
    else
      @schedule = @event.schedule
    end

  end

  # POST /events
  # POST /events.json
  def create
    puts "running create"
    @event = current_user.events.create(event_params)
    # If no days are created init then forces creation of a blank schedule
    if @event.schedule.try(:days) == nil
      @schedule = @event.create_schedule(event_id: @event.id, user_id: current_user.id)
    end
  
    #@schedule.days.create


    

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @event.user_id == current_user.id
      respond_to do |format|
        # puts "call sanitize_url"
        # sanitize_url
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "Not allowed"
      redirect_to root_path
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if @event.user_id == current_user.id
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:error] = "Not allowed"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :name, :description, :uploaded_file_file_name,
        links_attributes: [:id, :label, :url, :_destroy],
        assets_attributes: [:id, :event_id, :uploaded_file, :uploaded_file_file_name, :_destroy], 
        schedule_attributes: [:id, :_destroy, 
          days_attributes: [:id, :date, :_destroy,
            dayevents_attributes: [:id, :title, :start, :stop, :description, :_destroy]]]
        )
    end


end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def home
  end

  def about
  end

  def help
  end
  
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/events/Old.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#tab1">Tab1e</a></li>
  <li role="presentation"><a href="#tab2">Tab2</a></li>
  <li role="presentation"><a href="#tab3">tab3</a></li>
</ul>
<div id="tab1", style="display: none;">tab1 content</div>
<div id="tab2" style="display: none;">tab2 contentsladfk asdf</div>
<div id="tab3" style="display: none;">tab ington 3 content</div>

<%= @event %>

<%= @schedule %>

<div class="nested-fields">
	<%= f.input :date, input_html: { class: "form-input form-control" } %>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	<hr>
</div>








<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Collapse</h2>


  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Collapsible Group 1</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Collapsible Group 2</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Collapsible Group 3</a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
      </div>
    </div>
  </div> 

  
</div>

app/views/events/_asset_fields.html.erb
<div class="nested-fields">
	<%= f.file_field :uploaded_file %>
	<br>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	<hr>
</div>

app/views/events/_day_fields.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Add New Date</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>

<%= @event %>

<%= @schedule %>

<div class="nested-fields">
	<%= f.input :date, input_html: { class: "form-input form-control" } %>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	<hr>
</div>

app/views/events/_day_fields.html.erb
<div class="nested-fields">
	<div class="form-inline">
		<%= f.input :date, date_select: { class: "form-input form-control" } %>
		<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	</div>
	<br>
	<%= f.simple_fields_for :dayevents do |devent| %>
		<%= render 'dayevent_fields', f: devent %>
	<% end %>

	<div class="links" style="margin-left: 60px;">

		<%= link_to_add_association 'Add Event', f, :dayevents, class: "btn btn-default btn-sm add-button" %>
	</div>
	<hr>		
</div>

app/views/events/_dayevent_fields.html.erb
<div class="nested-fields" style="margin-left: 60px;">
	<%= f.input :title, input_html: { class: "form-input form-control input-sm" } %>
	<div class="form-inline">
		<%= f.input :start, label: 'Begins', input_html: { class: 'form-input form-control input-sm' } %>
		<%= f.input :stop, label: 'Ends', input_html: { class: "form-input form-control input-sm" } %>
	</div>
	<%= f.input :description, input_html: { class: "form-input form-control input-sm" } %>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default btn-sm" %>
	<hr>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
	<%= f.error_notification %>

	<div class="form-inputs">
		<%= f.input :name %>
		<%= f.input :description %>
		<hr>
	</div>
	
	<div class="panel-group" id="accordion">

		<div class="panel panel-default">
	      <div class="panel-heading">
	      	<h4 class="panel-title", style="text-align: center;">
	         	<a data-toggle="collapse" data-parent="#accordion" href="#schedule">Event Schedule</a>
	         </h4>
	      </div>
	      <div id="schedule" class="panel-collapse collapse">
	      	<div class="panel-body">
					<br>
					<%= f.simple_fields_for :schedule do |schedule| %>
						<%= render 'schedule_fields', f: schedule %>
					<% end %>
	      	</div>
	      </div>
	   </div>

		<hr>
		
		<div class="panel panel-default">
	      <div class="panel-heading">
	      	<h4 class="panel-title" style="text-align: center;">
	         	<a data-toggle="collapse" data-parent="#accordion" href="#linksExpand">Event Links</a>
	         </h4>
	      </div>
	      <div id="linksExpand" class="panel-collapse collapse">
	      	<div class="panel-body">
					<br>
					<div class="nested-fields">
						<%= f.simple_fields_for :links do |link| %>
							<%= render 'link_fields', f: link %>
						<% end %>
					</div>
					<div class="links">
						<%= link_to_add_association 'Add Link', f, :links, class: "btn btn-block btn-default add-buton" %>
					</div>
	      	</div>
	      </div>
	   </div>

	   <hr>
		
		<div class="panel panel-default">
	      <div class="panel-heading">
	      	<h4 class="panel-title" style="text-align: center;">
	         	<a data-toggle="collapse" data-parent="#accordion" href="#upload">Upload Shared Files</a>
	         </h4>
	      </div>
	      <div id="upload" class="panel-collapse collapse">
	      	<div class="panel-body">
					<br>
					<p>
						Warning! All uploaded files will be public!
					</p>
						<%= f.simple_fields_for :assets, :html => { :multipart => true } do |asset| %>
							<%= render 'asset_fields', f: asset %>
						<% end %>
						<div class="links">
						<%= link_to_add_association 'Add file', f, :assets, class: "btn btn-block btn-default add-buton" %>
					</div>
					
	      	</div>
	      </div>
	   </div>

	</div>

	<div class="form-actions" style="padding: 0px 0px 15px 0px;">
		<hr>
		<%= f.button :submit %>
		<%= link_to 'Back', events_path, class: "btn btn-default", style: "margin-left: 10px;" %>
	</div>

<% end %>

app/views/events/_link_fields.html.erb
<div class="nested-fields">
	<%= f.input :label, input_html: { class: "form-input form-control" } %>
	<%= f.input :url, input_html: { class: "form-input form-control" } %>
	<%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
	<hr>
</div>

app/views/events/_schedule_fields.html.erb
<div class=" nested-fields">
	<%= f.simple_fields_for :days do |day| %>
		<%= render 'day_fields', f: day %>
	<% end %>
</div>
<div class="links">
	<%= link_to_add_association 'Add Day', f, :days, class: "btn btn-block btn-default add-buton" %>
</div>

app/views/events/edit.html.erb
<h1 align="center">Editing <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1 align="center">My Events</h1>
<hr>

<% @events.each do |event| %>
  <div class="row">
    <div class="col-md-6">
      <h4><%= event.name %></h4>
    </div>
    <div class="col-md-2">
      <h4><%= link_to 'Show', event %></h4>
    </div>
    <div class="col-md-2">
      <h4><%= link_to 'Edit', edit_event_path(event) %></h4>
    </div>
    <div class="col-md-2">
      <h4><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></h4>
    </div>
  </div>
<% end %>

<br>

<%= link_to 'New Event', new_event_path, class: "btn btn-default btn-lg" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
	<h1 align="center">
	  <%= @event.name %>
	</h1>
	<br/>
	<h4>
	  <%= @event.description %>
	</h4>
</div>
<br/>
<div class="row">
	<% @event.links.each do |link| %>
			<%= link_to link.label, link.url, target: "_blank", class: "btn btn-default btn-lg" %>
	<% end %>
</div>
<br/>
<div class="row">
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
	      <div class="panel-heading">
	      	<h4 class="panel-title", style="text-align: center;">
	         	<a data-toggle="collapse" data-parent="#accordion" href="#schedule">Event Schedule</a>
	         </h4>
	      </div>

	      <div id="schedule" class="panel-collapse collapse">
	      	<div class="panel-body">

				  <ul class="nav nav-tabs">
				   <% @event.schedule.days.each_with_index do |day, index| %>
				    	<% if index == 0 %>
				    		<li class="active"><a href="#<%= day.id %>" data-toggle="tab"><%= day.date.strftime("%d %B") %></a></li>
				    	<% else %>
				    		<li><a href="#<%= day.id %>" data-toggle="tab"><%= day.date.strftime("%d %B") %></a></li>
				    	<% end %>
				   <% end %>
				  </ul>

				  <div class="tab-content">
				  	<% @event.schedule.days.each_with_index do |day, index| %>
				    	<% if index == 0 %>
				    		<div id="<%= day.id %>" class="tab-pane fade in active">
				    			<% day.dayevents.order("start ASC").each do |event| %>
							      <h3><%= event.title %></h3>
							      <h4>From <%= event.start.strftime("%l:%M %p") %> to <%= event.stop.strftime("%l:%M %p") %></h4>
							      <p><%= event.description %></p>
							      <hr>
						      <% end %>
						  	</div>
				    	<% else %>
				    		<div id="<%= day.id %>" class="tab-pane fade">
						      <% day.dayevents.order("start ASC").each do |event| %>
							      <h3><%= event.title %></h3>
							      <h4>     From <%= event.start.strftime("%l:%M %p") %> to <%= event.stop.strftime("%l:%M %p") %></h4>
							      <p>     <%= event.description %></p>
							      <hr>
						      <% end %>
						  	</div>
				    	<% end %>
				   <% end %>
				  </div>
	      	</div>
	      </div>
	   </div>

	   <br/>

	   <div class="panel panel-default">
	      <div class="panel-heading">
	      	<h4 class="panel-title", style="text-align: center;">
	         	<a data-toggle="collapse" data-parent="#accordion" href="#uploads">Uploaded Files</a>
	         </h4>
	      </div>
	      <div id="uploads" class="panel-collapse collapse">
	      	<div class="panel-body">
					<table> 
						<tr>
							<td><h4 align="center">Uploaded Files</h4></td>
						</tr>
						<% @event.assets.each do |asset| %>
							<tr> 
								<td><%= link_to asset.file_name, asset.uploaded_file.url %></td> 
							</tr> 
							<% end %> 
					</table> 
	      	</div>
	      </div>
	   </div>
	</div>
</div>
<div class="row">
	<br>
	<% if current_user.id == @event.user_id %>
		<%= link_to "Edit", edit_event_path(@event), class: "btn btn-default" %>  
		<%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>  
	<% end %>
	<%= link_to 'Back', events_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Event Dashboard</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="nav navbar navbar-default">
			<div class="container">
				<div class="navbar-brand" ><%= link_to "Event Dashboard", root_path %></div>
				<% if user_signed_in? %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "New Event", new_event_path %></li>
						<li><%= link_to "Account", edit_user_registration_path %></li>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					</ul>
				<% else %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<li><%= link_to "Sign In", new_user_session_path %></li>
					</ul>
				<% end %>
			</div>
		</div>
		
		<div class="container">
			<div class="col-md-6 col-md-offset-3">
				<% flash.each do |name, msg| %>
					<div class="alert alert-info fade in">
				    <button class="close" data-dismiss="alert">×</button>
				    <%= msg %>
				  </div>
				<% end %>
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/page/about.html.erb
<h1>About</h1>
<p>Find me in app/views/page/about.html.erb</p>
<p>This will be the first page seen when users are not logged in yet</p>
<p>After an account is created they will see their account page.</p>

app/views/page/help.html.erb
<h1>Page#help</h1>
<p>Find me in app/views/page/help.html.erb</p>

app/views/page/home.html.erb
<div id="home", align="center">
	<h1 align="center">Your Event Hub</h1>
	<br>
	<h4 align="center">The simple app that makes event organization easy!</h4>
	<br>
	<hr>
	<br>
	<div >
	<p>
		Organize and share event information with your patrons from one convenient location.
	</p>
	<br>
	<p>
		Create an account to get started!
	</p>
	<br>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-lg" %>
</div>

app/views/schedule/edit.html.erb
<h1 align="center">Editing <%= @event.name %> Schedule</h1>

<%= render 'form' %>